/* Prüfungstrainer – Service Worker: App-Shell offline verfügbar machen */
var CACHE = "pruefungstrainer-v9";
var ASSETS = [
  "./",
  "./index.html",
  "./styles.css",
  "./app.js",
  "./schema-br-beamtenverhaeltnis.js",
  "./schema-br-laufbahnbewerber.js",
  "./schema-br-befoerderung.js",
  "./schema-br-ernennungsfaelle.js",
  "./schema-br-ernennung-voraussetzungen.js",
  "./schema-br-ernennungsurkunde.js",
  "./schema-br-fehlerfolgen-ernennung.js",
  "./schema-br-nichtigkeit.js",
  "./schema-br-ruecknahme.js",
  "./schema-br-beendigung.js",
  "./schema-br-entlassung-gesetz.js",
  "./schema-br-entlassung-va.js",
  "./schema-br-ruhestand.js",
  "./schema-br-pflichten.js",
  "./schema-br-remonstration.js",
  "./schema-br-rechte.js",
  "./schema-br-dienstvergehen.js",
  "./schema-br-disziplinarverfahren.js",
  "./schema-br-nebentaetigkeit.js",
  "./schema-br-personalverteilung.js",
  "./schema-br-rechtsschutz.js",
  "./schema-baugenehmigung.js",
  "./schema-bauaufsicht.js",
  "./schema-nachbarschutz.js",
  "./schema-einschreiten.js",
  "./schema-bebauungsplan.js",
  "./schema-plansicherung.js",
  "./schema-komr-aufgaben.js",
  "./schema-komr-selbstverwaltung.js",
  "./schema-komr-kommunalaufsicht.js",
  "./schema-komr-satzung.js",
  "./schema-komr-organkompetenz.js",
  "./schema-komr-ratsbeschluss.js",
  "./schema-komr-mitwirkungsverbot.js",
  "./schema-komr-aussetzung.js",
  "./schema-komr-bmwahl.js",
  "./schema-komr-beigeordnete.js",
  "./schema-komr-wahlbeschwerde.js",
  "./schema-komr-kvs.js",
  "./schema-komr-einrichtungen.js",
  "./schema-komr-verpflichtungserklaerung.js",
  "./schema-avr-va-begriff.js",
  "./schema-avr-wirksamkeit.js",
  "./schema-avr-rechtmaessigkeit.js",
  "./schema-avr-fehlerfolgen.js",
  "./schema-avr-ermessen.js",
  "./schema-avr-nebenbestimmungen.js",
  "./schema-avr-ws-zulaessigkeit.js",
  "./schema-avr-ws-begruendetheit.js",
  "./schema-avr-verwaltungsvorschriften.js",
  "./schema-avr-aufhebung.js",
  "./schema-avr-zusicherung.js",
  "./schema-avr-oerv.js",
  "./schema-avr-anfechtungsklage.js",
  "./schema-avr-verpflichtungsklage.js",
  "./schema-avr-leistungsklage.js",
  "./schema-avr-feststellungsklage.js",
  "./schema-avr-ffk.js",
  "./schema-avr-80v.js",
  "./schema-avr-123.js",
  "./schema-avr-beitreibung.js",
  "./schema-avr-amtshaftung.js",
  "./schema-avr-folgenbeseitigung.js",
  "./schema-pr-anspruch.js",
  "./schema-pr-geschaeftsfaehigkeit.js",
  "./schema-pr-stellvertretung.js",
  "./schema-pr-fristen.js",
  "./schema-pr-verjaehrung.js",
  "./schema-pr-eigentumserwerb.js",
  "./schema-pr-herausgabe.js",
  "./schema-pr-bereicherung.js",
  "./schema-pr-delikt.js",
  "./schema-pr-unmoeglichkeit.js",
  "./schema-pr-schadensersatz.js",
  "./schema-pr-glaeubigerverzug.js",
  "./schema-pr-kauf-nacherfuellung.js",
  "./schema-pr-kauf-ruecktritt.js",
  "./schema-pr-kauf-schadensersatz.js",
  "./schema-pr-grundstueck.js",
  "./schema-sr-freiheitsgrundrechte.js",
  "./schema-sr-gleichheitsgrundrechte.js",
  "./schema-sr-menschenwuerde.js",
  "./schema-sr-apr.js",
  "./schema-sr-versammlungsfreiheit.js",
  "./schema-sr-berufsfreiheit.js",
  "./schema-sr-verfassungsbeschwerde.js",
  "./schema-sr-gesetzgebungskompetenz.js",
  "./schema-sr-gesetzgebungsverfahren.js",
  "./schema-sr-abgeordnete.js",
  "./schema-sr-wahlrechtsgrundsaetze.js",
  "./schema-sr-bundesrat.js",
  "./schema-sr-regierung.js",
  "./schema-sr-bundespraesident.js",
  "./schema-sr-verfassungsaenderung.js",
  "./schema-sr-bundesstaat.js",
  "./schema-sr-rechtsstaat.js",
  "./schema-sr-eur-rechtsquellen.js",
  "./schema-sr-eur-richtlinie.js",
  "./schema-sr-eur-vorrang.js",
  "./schema-sr-eur-grundfreiheiten.js",
  "./schema-atr-anwendbarkeit.js",
  "./schema-atr-rangordnung.js",
  "./schema-atr-arbeitnehmer.js",
  "./schema-atr-arbeitsvertrag.js",
  "./schema-atr-befristung.js",
  "./schema-atr-probezeit.js",
  "./schema-atr-beschaeftigungszeit.js",
  "./schema-atr-beendigung.js",
  "./schema-atr-ordentliche-kuendigung.js",
  "./schema-atr-ausserordentliche-kuendigung.js",
  "./schema-atr-eingruppierung.js",
  "./schema-atr-stufenzuordnung.js",
  "./schema-atr-stufenaufstieg.js",
  "./schema-atr-hoehergruppierung.js",
  "./schema-atr-zulage.js",
  "./schema-atr-jahressonderzahlung.js",
  "./schema-atr-entgelt-auszahlung.js",
  "./schema-atr-entgeltfortzahlung.js",
  "./schema-atr-krankengeldzuschuss.js",
  "./schema-atr-nachweispflichten.js",
  "./schema-atr-erholungsurlaub.js",
  "./schema-atr-urlaubsuebertragung.js",
  "./schema-atr-zusatzurlaub.js",
  "./schema-atr-arbeitsbefreiung.js",
  "./schema-besr-alimentation.js",
  "./schema-besr-bestandteile.js",
  "./schema-besr-anspruch.js",
  "./schema-besr-teilmonat.js",
  "./schema-besr-teilzeit.js",
  "./schema-besr-fernbleiben.js",
  "./schema-besr-rueckforderung.js",
  "./schema-besr-besoldungsgruppe.js",
  "./schema-besr-stufenbeginn.js",
  "./schema-besr-stufenaufstieg.js",
  "./schema-besr-befoerderung-stufe.js",
  "./schema-besr-paz.js",
  "./schema-besr-kbz.js",
  "./schema-besr-sonderzuschlaege-fz.js",
  "./schema-besr-zulagen.js",
  "./schema-besr-ausgleichszulage.js",
  "./schema-besr-anwaerterbezuege.js",
  "./manifest.webmanifest",
  "./icons/icon.svg",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/apple-touch-icon.png"
];

self.addEventListener("install", function (e) {
  e.waitUntil(
    caches.open(CACHE).then(function (c) { return c.addAll(ASSETS); })
      .then(function () { return self.skipWaiting(); })
  );
});

self.addEventListener("activate", function (e) {
  e.waitUntil(
    caches.keys().then(function (keys) {
      return Promise.all(keys.filter(function (k) { return k !== CACHE; })
        .map(function (k) { return caches.delete(k); }));
    }).then(function () { return self.clients.claim(); })
  );
});

self.addEventListener("fetch", function (e) {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then(function (hit) {
      return hit || fetch(e.request).then(function (resp) {
        var copy = resp.clone();
        caches.open(CACHE).then(function (c) { c.put(e.request, copy); });
        return resp;
      });
    })
  );
});
